trigger:
- master

variables:
  BUILD_COMMIT: 49153b5a58a97935cfcfd2b0b6578ff33f2f6202
  ANACONDA_ORG: ofajardo
  # set Anaconda token in azure

jobs:
  - template: azure/posix.yml
    parameters:
      name: macOS
      vmImage: macOS-11
      matrix:
        py_3.8_64_arm64:
          MB_PYTHON_VERSION: "3.8"
          MB_PYTHON_OSX_VER: "10.9"
          PLAT: arm64
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        py_3.8_64:
          MB_PYTHON_VERSION: "3.8"
          MB_PYTHON_OSX_VER: "10.9"

